spring:
    datasource:
        url: jdbc:sqlserver://localhost;database=DataUserBasic
        username: bee
        password: bee
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServer2012Dialect